openapi: 3.0.0
info:
  title: U1-M4 Summative / REST Random Response Service
  description: This web service is a quote-of-the-day, word-of-the-day, and magic 8-ball service.
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local dev server
paths:
  /quote:
    get:
      summary: returns a randomly generated quote and author as json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quote'
  /word:
    get:
      summary: returns a random word-of-the-day and definition as json
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Definition'
  /magic:
    post:
      summary: takes in a user-defined question as json in the request body, and returns a randomly-generated answer as json
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Answer'
        '400':
          description: Bad Request
components:
  schemas:
    Quote:
      properties:
        author:
          type: string
        quote:
          type: string
    Definition:
      properties:
        word:
          type: string
        definition:
          type: string
    Answer:
      properties:
        question:
          type: string
        answer:
          type: string
    Question:
      properties:
        question:
          type: string